// app/terms/page.js
// SecureIT360 - Terms of Service

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-gray-900">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-8">
          <a href="/" className="text-red-600 hover:text-red-700 text-sm font-medium">Back to SecureIT360</a>
        </div>
        <h1 style={{fontSize:'26px', fontFamily:'Arial', color:'#000', marginBottom:'8px'}}>TERMS OF SERVICE</h1>
        <p style={{color:'#595959', fontSize:'14px', marginBottom:'32px'}}><strong>Last updated April 10, 2026</strong></p>

        <div style={{fontFamily:'Arial', fontSize:'14px', color:'#595959', lineHeight:'1.8'}}>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>1. AGREEMENT TO TERMS</h2>
          <p>By accessing or using SecureIT360, operated by Global Cyber Assurance Ltd, you agree to be bound by these Terms of Service. If you do not agree, do not use our services. These terms apply to all users including businesses and their representatives.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>2. DESCRIPTION OF SERVICES</h2>
          <p>SecureIT360 is a cyber security platform for small and medium businesses in New Zealand, Australia and the Pacific region. It provides automated security scanning, risk scoring, regulatory compliance mapping and guided remediation services. The platform is operated by Global Cyber Assurance Ltd.</p>
          <p>Services are provided for internal business use only. You may not use the platform for personal use or resale.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>3. GOVERNING LAW AND JURISDICTION</h2>
          <p>These terms are governed by the laws of Australia. For clients based in New Zealand, the laws of New Zealand apply. For clients based in India, the laws of India apply. For clients based in the United Arab Emirates, the laws of the UAE apply. Disputes will be resolved by informal negotiation first, followed by arbitration in Sydney, Australia if unresolved within 30 days.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>4. ACCOUNTS AND REGISTRATION</h2>
          <p>You must provide accurate information when registering. You are responsible for maintaining the security of your account credentials. You must notify us immediately of any unauthorised access. One account per business domain is permitted.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>5. DOMAIN SCANNING</h2>
          <p>By adding a domain to the platform you confirm you own or have explicit authority to scan that domain. You must not scan domains belonging to other organisations without their written permission. Global Cyber Assurance Ltd accepts no liability for unauthorised scanning by users.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>6. PAYMENTS AND BILLING</h2>
          <p>Subscriptions are billed monthly in your local currency (NZD, AUD, INR, or AED as applicable based on your registration country). All prices are exclusive of applicable taxes including GST/VAT. Payments are processed securely by Stripe. We accept Visa, Mastercard, and American Express.</p>
          <p>Subscriptions automatically renew each month unless cancelled. You may cancel at any time by logging into your account settings or contacting us at governance@secureit360.co. No refunds are provided for the current billing period already paid.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>7. FREE TRIAL</h2>
          <p>A 7-day free trial is available for new accounts. The trial includes access to Dark Web and Email Security scan engines only. No credit card is required for the trial. At the end of the trial period, you must subscribe to continue accessing the platform.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>8. SECURITY FINDINGS DISCLAIMER</h2>
          <p>All security findings, risk scores, governance scores, compliance assessments, and penalty estimates generated by the platform are for awareness purposes only. They do not constitute legal advice, financial advice, or a guarantee of security. Global Cyber Assurance Ltd recommends seeking independent legal advice regarding your specific compliance obligations.</p>
          <p>Penalty figures shown are indicative maximums based on current legislation as at April 2026 and may vary based on individual circumstances.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>9. PROHIBITED ACTIVITIES</h2>
          <p>You must not:</p>
          <ul style={{marginLeft:'20px', marginBottom:'12px'}}>
            <li>Scan domains you do not own or have explicit permission to scan</li>
            <li>Use scan results for any purpose other than improving your own business security</li>
            <li>Share access credentials with unauthorised users</li>
            <li>Attempt to reverse engineer or circumvent the platform security measures</li>
            <li>Use the platform for any unlawful purpose</li>
          </ul>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>10. INTELLECTUAL PROPERTY</h2>
          <p>All content, software, algorithms, and materials on the platform are the intellectual property of Global Cyber Assurance Ltd. You may not copy, reproduce, or distribute any part of the platform without written permission.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>11. DATA AND PRIVACY</h2>
          <p>Your use of the platform is also governed by our Privacy Policy at <a href="https://app.secureit360.co/privacy" style={{color:'#dc2626'}}>https://app.secureit360.co/privacy</a>. All client data is stored in Sydney, Australia on Supabase infrastructure (ap-southeast-2 region) and encrypted using AES-256 encryption.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>12. LIMITATION OF LIABILITY</h2>
          <p>To the maximum extent permitted by law, Global Cyber Assurance Ltd's total liability to you for any claim arising from these terms or your use of the platform is limited to the amount you paid us in the 6 months preceding the claim. We are not liable for any indirect, incidental, special, or consequential damages.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>13. SERVICE AVAILABILITY</h2>
          <p>We aim to provide 99.5% uptime but do not guarantee uninterrupted service. We may perform maintenance that temporarily affects availability. We will endeavour to provide advance notice of scheduled maintenance.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>14. TERMINATION</h2>
          <p>We may suspend or terminate your account if you breach these terms, fail to pay, or engage in prohibited activities. You may terminate your account at any time through your account settings. Upon termination, your data will be deleted within 30 days.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>15. CHANGES TO TERMS</h2>
          <p>We may update these terms from time to time. We will notify you of material changes by email. Continued use of the platform after changes constitutes acceptance of the new terms.</p>

          <h2 style={{fontSize:'19px', color:'#000', marginTop:'32px', marginBottom:'12px'}}>16. CONTACT US</h2>
          <p>For questions about these terms, contact us at:</p>
          <p>Global Cyber Assurance Ltd<br/>300 Richmond Road<br/>Grey Lynn<br/>Auckland 1021<br/>New Zealand<br/><a href="mailto:governance@secureit360.co" style={{color:'#dc2626'}}>governance@secureit360.co</a></p>

        </div>
      </div>
    </div>
  )
}
